---
"🆙 changelog":
  - .github/workflows/changelog.yaml
  - .github/workflows/release.yaml
  - changelog.md

"👷 CI/CD":
  - .github/**/*
  - .github/workflows/release.yaml
  - .bumpversion.cfg
  - .gitignore

"📦 dependencies":
  - .github/dependabot.yaml
  - poetry.lock
  - pyproject.toml

"📗 documentation":
  - .github/**/*label*
  - .github/workflows/docs.yaml
  - .github/code-of-conduct.md
  - .mailmap
  - license
  - readme.md

"💖 sponsor":
  - .github/funding.yml