flowchart TD
    classDef missing stroke-dasharray: 5
    a[a\n3.4.0]
    b[b\n2.3.1]
    c[c\n5.10.0]
    d[d\n2.35]
    e[e\n0.12.1]
    f[f\n3.1]
    g[g\n6.8.3rc1]
    a -- >=2.0.0 --> b
    a -- >=5.7.1 --> c
    b -- >=2.30,<2.42 --> d
    c -- >=0.12.1 --> e
    c -- >=2.30 --> d
    d -- >=0.9.0 --> e
    f -- >=2.1.0 --> b
    g -- >=0.9.0 --> e
    g -- >=3.0.0 --> f