flowchart LR
    click_extra[["`click-extra`"]]

    subgraph primary-deps [Primary dependencies]
        extra_platforms{{"`extra-platforms`"}}
        requests{{"`requests`"}}
        cloup{{"`cloup`"}}
        click_0{{"`click`"}}
        tabulate{{"`tabulate`"}}
        wcmatch{{"`wcmatch`"}}
        tomli{{"`tomli`"}}
        boltons{{"`boltons`"}}
        deepmerge{{"`deepmerge`"}}
    end

    colorama(["`colorama`"])
    typing_extensions(["`typing-extensions`"])
    bracex(["`bracex`"])
    certifi(["`certifi`"])
    charset_normalizer(["`charset-normalizer`"])
    idna(["`idna`"])
    urllib3(["`urllib3`"])
    wcwidth(["`wcwidth`"])

    subgraph ext_hjson [--extra hjson]
        hjson{{"`hjson >=3.1`"}}
    end

    subgraph ext_json5 [--extra json5]
        json5{{"`json5 >=0.12.1`"}}
    end

    subgraph ext_jsonc [--extra jsonc]
        json_with_comments{{"`json-with-comments >=1.2.10`"}}
    end

    subgraph ext_mkdocs [--extra mkdocs]
        mkdocs{{"`mkdocs >=1.4`"}}
        mkdocs_get_deps(["`mkdocs-get-deps`"])
        pyyaml{{"`pyyaml`"}}
        jinja2(["`jinja2`"])
        packaging(["`packaging`"])
        ghp_import(["`ghp-import`"])
        markdown(["`markdown`"])
        markupsafe(["`markupsafe`"])
        mergedeep(["`mergedeep`"])
        pygments{{"`pygments >=2.14`"}}
        pymdown_extensions{{"`pymdown-extensions >=10`"}}
        python_dateutil(["`python-dateutil`"])
        pyyaml_env_tag(["`pyyaml-env-tag`"])
        pathspec(["`pathspec`"])
        platformdirs(["`platformdirs`"])
        six(["`six`"])
        watchdog(["`watchdog`"])
    end

    subgraph ext_pytest [--extra pytest]
        pytest{{"`pytest >=9`"}}
        exceptiongroup(["`exceptiongroup`"])
        iniconfig(["`iniconfig`"])
        pluggy(["`pluggy`"])
    end

    subgraph ext_sphinx [--extra sphinx]
        sphinx{{"`sphinx >=8`"}}
        alabaster(["`alabaster`"])
        babel(["`babel`"])
        docutils{{"`docutils >=0.20`"}}
        imagesize(["`imagesize`"])
        roman_numerals(["`roman-numerals`"])
        snowballstemmer(["`snowballstemmer`"])
        sphinxcontrib_applehelp(["`sphinxcontrib-applehelp`"])
        sphinxcontrib_devhelp(["`sphinxcontrib-devhelp`"])
        sphinxcontrib_htmlhelp(["`sphinxcontrib-htmlhelp`"])
        sphinxcontrib_jsmath(["`sphinxcontrib-jsmath`"])
        sphinxcontrib_qthelp(["`sphinxcontrib-qthelp`"])
        sphinxcontrib_serializinghtml(["`sphinxcontrib-serializinghtml`"])
    end

    subgraph ext_toml [--extra toml]
        tomlkit{{"`tomlkit >=0.13`"}}
    end

    subgraph ext_xml [--extra xml]
        xmltodict{{"`xmltodict >=1`"}}
    end

    click_extra ==>|" >=2.32.4 "| requests
    click_extra ==>|" >=8.3.1 "| click_0
    click_extra ==>|" >=3.0.7 "| cloup
    click_extra ==>|" >=2 "| tomli
    click_extra ==>|" >=5 "| extra_platforms
    click_extra ==>|" >=0.9 "| tabulate
    click_extra ==>|" >=10 "| wcmatch
    click_extra ==>|" >=20 "| boltons
    click_extra ==>|" >=1.0.1 "| deepmerge
    sphinx ==> requests
    sphinx --> colorama
    sphinx --> jinja2
    sphinx --> packaging
    sphinx ==> pygments
    sphinx ==> tomli
    sphinx --> alabaster
    sphinx --> babel
    sphinx ==> docutils
    sphinx --> imagesize
    sphinx --> roman_numerals
    sphinx --> snowballstemmer
    sphinx --> sphinxcontrib_applehelp
    sphinx --> sphinxcontrib_devhelp
    sphinx --> sphinxcontrib_htmlhelp
    sphinx --> sphinxcontrib_jsmath
    sphinx --> sphinxcontrib_qthelp
    sphinx --> sphinxcontrib_serializinghtml
    mkdocs --> mkdocs_get_deps
    mkdocs ==> pyyaml
    mkdocs ==> click_0
    mkdocs --> colorama
    mkdocs --> jinja2
    mkdocs --> packaging
    mkdocs --> ghp_import
    mkdocs --> markdown
    mkdocs --> markupsafe
    mkdocs --> mergedeep
    mkdocs --> pyyaml_env_tag
    mkdocs --> pathspec
    mkdocs --> watchdog
    pytest --> colorama
    pytest --> packaging
    pytest --> exceptiongroup
    pytest ==> pygments
    pytest ==> tomli
    pytest --> iniconfig
    pytest --> pluggy
    requests --> certifi
    requests --> charset_normalizer
    requests --> idna
    requests --> urllib3
    mkdocs_get_deps ==> pyyaml
    mkdocs_get_deps --> mergedeep
    mkdocs_get_deps --> platformdirs
    click_0 --> colorama
    jinja2 --> markupsafe
    cloup ==> click_0
    cloup --> typing_extensions
    exceptiongroup --> typing_extensions
    ghp_import --> python_dateutil
    pymdown_extensions ==> pyyaml
    pymdown_extensions --> markdown
    python_dateutil --> six
    pyyaml_env_tag ==> pyyaml
    extra_platforms ==> pytest
    tabulate --> wcwidth
    wcmatch --> bracex
    click_extra -.-> ext_hjson
    click_extra -.-> ext_json5
    click_extra -.-> ext_jsonc
    click_extra -.-> ext_mkdocs
    click_extra -.-> ext_pytest
    click_extra -.-> ext_sphinx
    click_extra -.-> ext_toml
    click_extra -.-> ext_xml

    click alabaster "https://pypi.org/project/alabaster/" _blank
    click babel "https://pypi.org/project/babel/" _blank
    click boltons "https://pypi.org/project/boltons/" _blank
    click bracex "https://pypi.org/project/bracex/" _blank
    click certifi "https://pypi.org/project/certifi/" _blank
    click charset_normalizer "https://pypi.org/project/charset-normalizer/" _blank
    click click_0 "https://pypi.org/project/click/" _blank
    click click_extra "https://pypi.org/project/click-extra/" _blank
    click cloup "https://pypi.org/project/cloup/" _blank
    click colorama "https://pypi.org/project/colorama/" _blank
    click deepmerge "https://pypi.org/project/deepmerge/" _blank
    click docutils "https://pypi.org/project/docutils/" _blank
    click exceptiongroup "https://pypi.org/project/exceptiongroup/" _blank
    click extra_platforms "https://pypi.org/project/extra-platforms/" _blank
    click ghp_import "https://pypi.org/project/ghp-import/" _blank
    click hjson "https://pypi.org/project/hjson/" _blank
    click idna "https://pypi.org/project/idna/" _blank
    click imagesize "https://pypi.org/project/imagesize/" _blank
    click iniconfig "https://pypi.org/project/iniconfig/" _blank
    click jinja2 "https://pypi.org/project/jinja2/" _blank
    click json_with_comments "https://pypi.org/project/json-with-comments/" _blank
    click json5 "https://pypi.org/project/json5/" _blank
    click markdown "https://pypi.org/project/markdown/" _blank
    click markupsafe "https://pypi.org/project/markupsafe/" _blank
    click mergedeep "https://pypi.org/project/mergedeep/" _blank
    click mkdocs "https://pypi.org/project/mkdocs/" _blank
    click mkdocs_get_deps "https://pypi.org/project/mkdocs-get-deps/" _blank
    click packaging "https://pypi.org/project/packaging/" _blank
    click pathspec "https://pypi.org/project/pathspec/" _blank
    click platformdirs "https://pypi.org/project/platformdirs/" _blank
    click pluggy "https://pypi.org/project/pluggy/" _blank
    click pygments "https://pypi.org/project/pygments/" _blank
    click pymdown_extensions "https://pypi.org/project/pymdown-extensions/" _blank
    click pytest "https://pypi.org/project/pytest/" _blank
    click python_dateutil "https://pypi.org/project/python-dateutil/" _blank
    click pyyaml "https://pypi.org/project/pyyaml/" _blank
    click pyyaml_env_tag "https://pypi.org/project/pyyaml-env-tag/" _blank
    click requests "https://pypi.org/project/requests/" _blank
    click roman_numerals "https://pypi.org/project/roman-numerals/" _blank
    click six "https://pypi.org/project/six/" _blank
    click snowballstemmer "https://pypi.org/project/snowballstemmer/" _blank
    click sphinx "https://pypi.org/project/sphinx/" _blank
    click sphinxcontrib_applehelp "https://pypi.org/project/sphinxcontrib-applehelp/" _blank
    click sphinxcontrib_devhelp "https://pypi.org/project/sphinxcontrib-devhelp/" _blank
    click sphinxcontrib_htmlhelp "https://pypi.org/project/sphinxcontrib-htmlhelp/" _blank
    click sphinxcontrib_jsmath "https://pypi.org/project/sphinxcontrib-jsmath/" _blank
    click sphinxcontrib_qthelp "https://pypi.org/project/sphinxcontrib-qthelp/" _blank
    click sphinxcontrib_serializinghtml "https://pypi.org/project/sphinxcontrib-serializinghtml/" _blank
    click tabulate "https://pypi.org/project/tabulate/" _blank
    click tomli "https://pypi.org/project/tomli/" _blank
    click tomlkit "https://pypi.org/project/tomlkit/" _blank
    click typing_extensions "https://pypi.org/project/typing-extensions/" _blank
    click urllib3 "https://pypi.org/project/urllib3/" _blank
    click watchdog "https://pypi.org/project/watchdog/" _blank
    click wcmatch "https://pypi.org/project/wcmatch/" _blank
    click wcwidth "https://pypi.org/project/wcwidth/" _blank
    click xmltodict "https://pypi.org/project/xmltodict/" _blank

    style click_extra stroke-width:3px
    style boltons stroke-width:3px
    style click_0 stroke-width:3px
    style cloup stroke-width:3px
    style deepmerge stroke-width:3px
    style docutils stroke-width:3px
    style extra_platforms stroke-width:3px
    style hjson stroke-width:3px
    style json_with_comments stroke-width:3px
    style json5 stroke-width:3px
    style mkdocs stroke-width:3px
    style pygments stroke-width:3px
    style pymdown_extensions stroke-width:3px
    style pytest stroke-width:3px
    style pyyaml stroke-width:3px
    style requests stroke-width:3px
    style sphinx stroke-width:3px
    style tabulate stroke-width:3px
    style tomli stroke-width:3px
    style tomlkit stroke-width:3px
    style wcmatch stroke-width:3px
    style xmltodict stroke-width:3px

    style primary-deps fill:#1565C020,stroke:#42A5F5
    style ext_hjson fill:#7B1FA220,stroke:#BA68C8
    style ext_json5 fill:#7B1FA220,stroke:#BA68C8
    style ext_jsonc fill:#7B1FA220,stroke:#BA68C8
    style ext_mkdocs fill:#7B1FA220,stroke:#BA68C8
    style ext_pytest fill:#7B1FA220,stroke:#BA68C8
    style ext_sphinx fill:#7B1FA220,stroke:#BA68C8
    style ext_toml fill:#7B1FA220,stroke:#BA68C8
    style ext_xml fill:#7B1FA220,stroke:#BA68C8
