---
name: 🆙 Changelog & versions
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - main
    paths:
      - changelog.md
      - "**/pyproject.toml"
      - ".github/workflows/*.yaml"
      - uv.lock
  workflow_run:
    workflows:
      - "Build & release"
    types:
      - completed
    branches:
      - main

jobs:

  changelog:
    uses: kdeldycke/repomatic/.github/workflows/changelog.yaml@c48893dce010cb24303044880ab40f571b7bebda # v6.21.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
