---
name: 🧹 Lint
"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - prepare-release
      - "renovate/**"

jobs:

  lint:
    uses: kdeldycke/workflows/.github/workflows/lint.yaml@v5.12.0
