---
name: 🚀 Build & release
"on":
  push:
    branches:
      - main

jobs:

  release:
    uses: kdeldycke/repomatic/.github/workflows/release.yaml@7b003a95093db88752f32cbcc1c736081821720d # v6.16.0
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
